### ISSUE TITLE
please update for ios 17 Privacy manifest - May 1, 2024 deadline

### ISSUE THREAD

**Issue by neiljaywarner** [mwaylabs/flutter-managed-configuration#10]
(thank you for updating to 1.0 by the way)

see: "AC6B.1
Declare this reason to access user defaults to read the com.apple.configuration.managed key to retrieve the managed app configuration set by MDM, or to set the com.apple.feedback.managed key to store feedback information to be queried over MDM, as described in the Apple Mobile Device Management Protocol Reference documentation."
from https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by danielkono** [comment]
closing with 1.1.0
