### ISSUE TITLE
[Documentation request] title/description from ios

### ISSUE THREAD

**Issue by neiljaywarner** [mwaylabs/flutter-managed-configuration#12]
Testing with testDPC lets you pull in values from https://github.com/mwaylabs/flutter-managed-configuration/blob/master/example/android/app/src/main/res/xml/app_restrictions.xml

is there an equivalent on ios or mac?
Thanks

**Comment by neiljaywarner** [comment]
Yes, i know this is a little out of scope but if this was a one stop shop for people doing the MDM "task" (or feature, stories, epic, whatever) that would be fantastic

**Comment by danielkono** [comment]
I cannot find any documentation besides [appconfig.org](https://www.appconfig.org/ios.html) which seems to be deprecated. It references to deprecated apple dev doc. Quick check on current apple doc, there is not hints that we can configure supported keys like for Android.
