### ISSUE TITLE
Android - Migrate plugin from JCenter to mavenCentral 

### ISSUE THREAD

**Issue by youssef-t-carl** [mwaylabs/flutter-managed-configuration#15]
Hello,

First of all, I would like to thank you for this package.

Currently,  JCenter will be shutdown on August 15th: [https://jfrog.com/blog/jcenter-sunset/](https://jfrog.com/blog/jcenter-sunset/)
JCenter will redirect to Maven starting on August 15th.

I think it would be better if this package looks for the dependency on mavenCentral instead of pointing on JCenter.
In `android/build.gradle`, we would have 
```
    repositories {
        google()
        mavenCentral()
    }
```
instead of 
```
    repositories {
        google()
        jcenter()
    }
```

For now, Android builds fail on CI because the dependency is on JCenter and the redirection is going to work starting on August 15th. Locally, it may work if all dependencies are in the cache. 

Thanks

**Comment by danielkono** [comment]
closing with 1.1.0
