### ISSUE TITLE
请问这个支持iOS mdm 管理吗？

### ISSUE THREAD

**Issue by org-lib** [mwaylabs/flutter-managed-configuration#2]
我看都只是安卓的注释

**Comment by danielkono** [comment]
Yes, this package supports managed configuration for iOS. Basically it reads out the NSUserDefaults with specific key: UserDefaults.standard.dictionary(forKey: "com.apple.configuration.managed").

How to deploy iOS apps with managed configuration, please check out  documentation on apple side.

**Comment by org-lib** [comment]
好的，我改天试试

danielkono ***@***.***>于2022年6月10日 周五下午10:06写道：
