### ISSUE TITLE
Update versions

### ISSUE THREAD

**Issue by AdrianDev0** [mwaylabs/flutter-managed-configuration#5]
Could you update your versions? I am getting errors from your library versions when trying to update my project to use the latest AGP version.

* Android Gradle plugin (AGP)
* Gradle wrapper
* Kotlin version
* compileSdkVersion
* Removing jcenter
* Update dependencies

**Comment by TomBeckett** [comment]
@danielkono any news on this? There's a few PRs to update the versions (Kotlin especially) that would be VERY helpful to get merged.

**Comment by danielkono** [comment]
with 1.0.0 coming updated android project files. Hope this fix your issues. If not feel free to reopen.
