### ISSUE TITLE
Could we got the defaultValue ?

### ISSUE THREAD

**Issue by darmawan01** [mwaylabs/flutter-managed-configuration#6]
Hi, Is there any way we can got the defaultValue from restrictions ?

I saw in docs example it set defaultValue for restriction. here is the docs

https://developer.android.com/work/managed-configurations#define-configuration

Thanks

**Comment by danielkono** [comment]
It would be possible to get the defined restrictions of the Android side but even then i don't see a way to get the defaultValue -> [getManifestRestrictions](https://developer.android.com/reference/android/content/RestrictionsManager#getManifestRestrictions(java.lang.String))
Another approach would be to check if there is an active restrictions provider or not, to decide if the config is default or from admin.  But this would only solve your request for a specific use case which i think is not sufficient. 

I would close this issue as from my point of view this is not resolvable.
